name = "PseudoTransientHMC"
uuid = "23ee6f83-38e1-4b4a-9f65-8b0f5e70fc17"
authors = ["Ludovic Räss <ludovic.rass@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
