name = "PseudoTransientHMC"
uuid = "23ee6f83-38e1-4b4a-9f65-8b0f5e70fc17"
authors = ["Ludovic Räss <ludovic.rass@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
MAT = "0.8"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
